api:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas: 3
  service:
    type: ClusterIP
  image:
    repository: ghcr.io/m3nowak/api
    tag: null
    pullPolicy: IfNotPresent
  configSecretRef: null
