version:  '3.8'
services:
  nats:
    image: docker.io/library/nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - rg-nats:/nats-data
      - ./compose/nats-server.conf:/etc/nats/nats-server.conf
    command: -c /etc/nats/nats-server.conf

  db:
    image: docker.io/library/postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rg-app-db:/var/lib/postgresql/data

  lgtm:
    image: docker.io/grafana/otel-lgtm:latest
    ports:
      - "3001:3000"
      - "4317:4317"
      - "4318:4318"

  prometheus-nats-exporter:
    image: docker.io/natsio/prometheus-nats-exporter:0.15.0
    command: ["-varz", "-jsz", "all", "http://nats:8222"]
    depends_on:
      - nats

  app-api:
    profiles:
      - "app"
    build:
      context: .
      dockerfile: Dockerfile
      target: all
    ports:
      - "8000:8000"
    volumes:
      - ./config/compose/api.yaml:/home/rgapp/config.yaml
    command: ["rg-api", "--config", "/home/rgapp/config.yaml"]
  
  app-db:
    profiles:
      - "app"
    build:
      context: .
      dockerfile: Dockerfile
      target: all
    command: ["rg-db", "migrate", "postgresql+psycopg://postgres:postgres@db/postgres"]
  
  app-nats-defs:
    profiles:
      - "app"
    build:
      context: .
      dockerfile: Dockerfile
      target: all
    command: ["rg-nats-defs","nats://nats:4222", "local", "--dev"]
  
  app-worker:
    profiles:
      - "app"
    build:
      context: .
      dockerfile: Dockerfile
      target: all
    volumes:
      - ./config/compose/worker.yaml:/home/rgapp/config.yaml
      - ./data/geo.db:/home/rgapp/geo.db
    command: ["rg-worker","--config", "/home/rgapp/config.yaml"]

  app-wha:
    profiles:
      - "app"
      - "wha"
    build:
      context: .
      dockerfile: Dockerfile
      target: all
    volumes:
      - ./config/compose/wha.yaml:/home/rgapp/config.yaml
    command: ["rg-wha", "--config", "/home/rgapp/config.yaml", "--no-register"]

volumes:
  rg-nats:
    external: true
  rg-app-db:
    external: true
