apiVersion: v1
kind: PersistentVolume
metadata:
  name: rg-app-worker-pv
  labels:
    app.kubernetes.io/part-of: rg-app
    app.kubernetes.io/name: worker
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /var/lib/rancher/k3s/storage/rg-app-worker
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rowerowegminy
