apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-pvc
  labels:
    app.kubernetes.io/part-of: rg-app
    app.kubernetes.io/name: worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: rg-app-worker-pv
  storageClassName: local-path
  volumeMode: Filesystem
