name: py-pdm-setup
description: |
  This installs python and pdm and installs dependencies.

runs:
  using: "composite"
  steps:
  - name: Set up Python 3.12
    uses: actions/setup-python@v4
    with:
      python-version: "3.12"
  - name: Install PDM
    run: pip install pdm
  - name: Install dependencies
    run: pdm install