apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: common-secrets-es
  labels:
    app.kubernetes.io/part-of: rg-app
spec:
  refreshInterval: 24h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-css
  target:
    name: common-secrets
    template:
      metadata:
        annotations: {}
        labels:
          app.kubernetes.io/part-of: rg-app
      data:
        postgres_password: |-
          {{ .postgres_password }}
        db_url: |-
          postgresql+psycopg://postgres:{{ .postgres_password }}@postgres-postgresql.postgres:5432/postgres
        db_cs: |-
          dbname=postgres host=postgres-postgresql.postgres user=postgres password={{ .postgres_password }}
        nats_creds: |-
          {{ .nats_common_creds }}
        strava_api_key: |-
          {{ .strava_api }}
        grafana_cloud: |-
          {{ .grafana_cloud }}
        api_secret: |-
          {{ .api_secret }}

  data:
    - secretKey: postgres_password
      remoteRef:
        key: /rowerowegminy/postgres-password
    - secretKey: nats_common_creds
      remoteRef:
        key: /rowerowegminy/nats-common-creds
    - secretKey: strava_api
      remoteRef:
        key: /rowerowegminy/strava-api
    - secretKey: grafana_cloud
      remoteRef:
        key: /rowerowegminy/grafana-cloud
    - secretKey: api_secret
      remoteRef:
        key: /rowerowegminy/api-secret
