apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret-es
  namespace: postgres
spec:
  refreshInterval: 24h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-css
  target:
    name: postgres-secret
    creationPolicy: Owner

  data:
    - secretKey: adminPasswordKey
      remoteRef:
        key: /rowerowegminy/postgres-password
