apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: leaf-ngs-secret-es
  namespace: nats
spec:
  refreshInterval: 24h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-css
  target:
    name: leaf-ngs-secret
    creationPolicy: Owner

  data:
    - secretKey: ngs.creds
      remoteRef:
        key: /rowerowegminy/nats-leaf
