apiVersion: v1
kind: Service
metadata:
  name: nats-metrics
  namespace: nats
  labels:
    app: nats-metrics
spec:
  ports:
    - port: 7777
      protocol: TCP
      targetPort: 7777
      name: metrics
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats
    app.kubernetes.io/name: nats
  type: ClusterIP
