apiVersion: v1
kind: ConfigMap
metadata:
  name: api
data:
  config.yaml: |
    http:
      port: 8000
    nats:
      url: "nats://nats.nats:4222"
      credsPath: "/home/rgapp/nats.creds"
    db:
      host: "postgres-postgresql.postgres"
      port: 5432
      user: "postgres"
      password:
        env: "POSTGRES_PASSWORD"
      database: "postgres"
    strava:
      clientId: "{{ .Values.clientId }}"
      clientSecret:
        env: "STRAVA_API_KEY"
    otel:
      useGrpc: true
      enabled: true
      svcName: "API"
      svcNs: "prod"
      endpoint: "alloy.alloy:4317"
    auth:
      secret:
        env: "API_SECRET"
    origins:
      - "https://rowerowegminy.pl"
