apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
  labels:
    app.kubernetes.io/part-of: rg-app
    app.kubernetes.io/name: db-seed
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      initContainers:
        - name: duck-db-obtain
          image: ghcr.io/m3nowak/rowerowe_gminy/geodb:latest
          command: ["cp", "/opt/geo.db", "/shared-data/geo.db"]
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data
      containers:
        - name: db-seed
          image: "ghcr.io/m3nowak/rowerowe_gminy/all:{{ .Values.imageVersion }}"
          command: ["rg-geo", "pg-export", "--db_path", "/shared-data/geo.db"]
          imagePullPolicy: Always
          env:
            - name: PG_CONN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: db_url
          volumeMounts:
            - name: shared-volume
              mountPath: /shared-data
      restartPolicy: OnFailure
      volumes:
        - name: shared-volume
          emptyDir: {}
  backoffLimit: 4
