apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: alloy
data:
  config.alloy: |
    logging {
      level  = "info"
      format = "logfmt"
    }
    otelcol.receiver.otlp "main" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }
      output {
        metrics = [otelcol.processor.batch.main.input]
        logs    = [otelcol.processor.batch.main.input]
        traces  = [otelcol.processor.batch.main.input]
      }
    }
    otelcol.processor.batch "main" {
      output {
        metrics = [otelcol.exporter.otlphttp.cloud.input]
        traces  = [otelcol.exporter.otlphttp.cloud.input]
        logs    = [otelcol.exporter.otlphttp.cloud.input]
      }
    }
    otelcol.auth.basic "cloud" {
      username = "1081162"
      password = sys.env("GRAFANA_CLOUD_API_KEY")
    }
    otelcol.exporter.otlphttp "cloud" {
      client {
        endpoint = "https://otlp-gateway-prod-eu-west-2.grafana.net/otlp"
        auth     = otelcol.auth.basic.cloud.handler
      }
    }
