apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud-es
  namespace: alloy
spec:
  refreshInterval: 24h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-css
  target:
    name: grafana-cloud
    creationPolicy: Owner

  data:
    - secretKey: password
      remoteRef:
        key: /rowerowegminy/grafana-cloud
