apiVersion: v1
kind: Service
metadata:
  name: alloy
  namespace: alloy
  labels:
    app.kubernetes.io/name: alloy
spec:
  selector:
    app.kubernetes.io/name: alloy
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      name: http-panel
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: grpc
    - protocol: TCP
      port: 4318
      targetPort: 4318
      name: http
  type: ClusterIP
