apiVersion: apps/v1
kind: Deployment
metadata:
  name: wha-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rg-wha
  template:
    metadata:
      labels:
        app: rg-wha
    spec:
      containers:
        - name: wha
          image: "ghcr.io/m3nowak/rowerowe_gminy/all:{{ .Values.imageVersion }}"
          imagePullPolicy: Always
          args:
            [
              "rg-wha",
              "--config",
              "/home/rgapp/config/config.yaml",
            ]
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            limits:
              cpu: "0.2"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          volumeMounts:
            - name: secret-volume
              mountPath: /home/rgapp/secret
              readOnly: true
            - name: config-volume
              mountPath: /home/rgapp/config
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: wha-secret
        - name: config-volume
          configMap:
            name: wha-config
