apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wha-secret-es
spec:
  refreshInterval: 24h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-css
  target:
    name: wha-secret
    creationPolicy: Owner

  data:
    - secretKey: strava-key
      remoteRef:
        key: /rowerowegminy/strava-api
    - secretKey: rg.creds
      remoteRef:
        key: /rowerowegminy/nats-wha-ngs-creds
    - secretKey: webhook-key
      remoteRef:
        key: /rowerowegminy/strava-webhook-verify-token
