apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: rg-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
