name: API Container
on: workflow_dispatch

jobs:
  use_template:
    uses: ./.github/workflows/container-template.yaml
    secrets: inherit
    with:
      target_image: api
      image_repo_base: ghcr.io/m3nowak/rowerowe_gminy
