name: Reusable PDM Job

on:
  workflow_call: {}

jobs:
  pdm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Install dependencies
        run: pdm install