# .github/workflows/template.yml
name: Container build template

on:
  workflow_call:
    inputs:
      target_image:
        required: true
        type: string

env:
  IMG_NAME_BASE: ghcr.io/m3nowak/rowerowe_gminy/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: What day is it?
      id: date
      run: echo "date=$(date +%F)" >> "$GITHUB_OUTPUT"
    - name: install python + pdm
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        curl -sSL https://pdm-project.org/install-pdm.py | python3 -
        pdm self add pdm-version
    - name: pdm install + version
      id: pdm_install
      run: |
        pdm install
        echo "version=$(pdm version)" >> "$GITHUB_OUTPUT"
    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
    - name: Build the Container image
      run: >
        podman build .
        --tag $IMG_NAME_BASE${{ inputs.target_image }}:${{ steps.pdm_install.outputs.version }}
        --tag $IMG_NAME_BASE${{ inputs.target_image }}:${{ steps.pdm_install.outputs.version }}-${{ steps.date.outputs.date }}
        --tag $IMG_NAME_BASE${{ inputs.target_image }}:${{ steps.pdm_install.outputs.version }}-${{ github.run_number }}
        --tag $IMG_NAME_BASE${{ inputs.target_image }}:latest
        --target api
    - name: Push the Container image to ghcr
      run: |
        podman login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.PACKAGES_TOKEN }}
        podman push $IMG_NAME_BASE${{ inputs.target_image }}:${{ steps.pdm_install.outputs.version }}
        podman push $IMG_NAME_BASE${{ inputs.target_image }}:${{ steps.pdm_install.outputs.version }}-${{ steps.date.outputs.date }}
        podman push $IMG_NAME_BASE${{ inputs.target_image }}:${{ steps.pdm_install.outputs.version }}-${{ github.run_number }}
        podman push $IMG_NAME_BASE${{ inputs.target_image }}:latest
