name: Create Geographical Data in DuckDB
on: workflow_dispatch

env:
  GEO_DIR: geo-data
  DDB_NAME: geo-data.db
  RCLONE_CFG_NAME: rg
  S3_BUCKET: rowerowegminy.pl
  #GML_PAK_URL: https://eu2.contabostorage.com/9556be5764414357ae3184b95da10055:rowerowegminy.pl/00_jednostki_administracyjne_gml.zip

  GML_PAK_URL: https://opendata.geoportal.gov.pl/prg/granice/00_jednostki_administracyjne_gml.zip
  ARTIFACT_NAME_DB: geodb
  ARTIFACT_NAME_TOPO: topo

  target_image: geodb
  image_repo_base: ghcr.io/m3nowak/rowerowe_gminy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download GML files
        run: |
          wget $GML_PAK_URL -O gml_pak.zip

      - name: Unzip GML files
        run: |
          mkdir -p $GEO_DIR
          unzip -j gml_pak.zip "00_jednostki_administracyjne_gml/*" -d $GEO_DIR

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Create GeoJSON files
        run: |
          # Find all .gml files and process each
          find $GEO_DIR -name "*.gml" -type f -print0 | xargs -0 -I {} pdm run rg-geo preprocess --path {}

      - name: Create DuckDB database
        run: pdm run rg-geo create-ddb --json_dir $GEO_DIR --db_path $DDB_NAME
      
      - name: Generate topology
        run: pdm run rg-geo mktopo --db_path $DDB_NAME --output topo.json

      - name: Topology gzip
        run: gzip topo.json

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_DB }} # From env
          path: ${{ env.DDB_NAME }} # From env
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_TOPO }}
          path: topo.json.gz

  s3-pub:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_DB }}
          path: ${{ env.DDB_NAME }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_TOPO }}
          path: topo.json.gz
      - name: Create Rclone config
        run: |
          cat << 'EOF' > rclone.conf
          ${{ secrets.RCLONE_S3_CFG }}
          EOF
      - name: Upload DuckDB database to S3
        run: rclone --config rclone.conf copy $DDB_NAME $RCLONE_CFG_NAME:$S3_BUCKET
      - name: Upload Topology to S3
        run: rclone --config rclone.conf copy topo.json $RCLONE_CFG_NAME:$S3_BUCKET
  
  container:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME_DB }}
          path: ${{ env.DDB_NAME }}
      - name: Reorganize downloaded artifact
        run: mv ${{ env.DDB_NAME }}/* geo.db
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      - name: What day is it?
        id: date
        run: echo "date=$(date +%F)" >> "$GITHUB_OUTPUT"
      - name: Build the Container image
        run: >
          podman build .
          --tag ${{ env.image_repo_base }}/${{ env.target_image }}:${{ steps.date.outputs.date }}
          --tag ${{ env.image_repo_base }}/${{ env.target_image }}:${{ github.run_number }}
          --tag ${{ env.image_repo_base }}/${{ env.target_image }}:latest
          --target ${{ env.target_image }}
          --build-arg dbpath=geo.db
      - name: Push the Container image to ghcr
        run: |
          podman login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.packages_token }}
          podman push ${{ env.image_repo_base }}/${{ env.target_image }}:${{ steps.date.outputs.date }}
          podman push ${{ env.image_repo_base }}/${{ env.target_image }}:${{ github.run_number }}
          podman push ${{ env.image_repo_base }}/${{ env.target_image }}:latest